                    name: Run Test Case
                    
                    on:
                      push:
                        branches:
                          - dev
                      pull_request:
                        branches:
                          - dev
                      workflow_dispatch:
                    
                    jobs:
                      initiating:
                        runs-on: ubuntu-latest
                        steps:
                          - uses: actions/checkout@v2
                          - name: start
                            run: echo "Start running test cases"
                            shell: bash